### ISSUE TITLE
Drm session exception

### ISSUE THREAD

**Issue by ravichaudhary133** [saifshaikh1805/tata-sky-m3u#17]
Unable to play any of the channels. Tivimate gives 'drm session exception' error.

**Comment by saifshaikh1805** [comment]
Fixed.

**Comment by mrblade** [comment]
I am still getting this. I have redeployed, tried logout and login, generated the playlist again but nothing seem to work
